# Buildpack API version
api = "0.5"

# Buildpack ID and metadata
[buildpack]
id = "dirigiblelabs/buildpacks-dirigible-cf"
version = "6.3.30"
name = "Eclipse Dirigible Cloud Foundry Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "org.eclipse.dirigible"
