name: Click-to-Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Install required packages
        run: |
          apt-get install pkg-config zip g++ zlib1g-dev unzip python
          wget https://github.com/bazelbuild/bazel/releases/download/0.19.1/bazel-0.19.1-installer-linux-x86_64.sh
          chmod +x bazel-0.19.1-installer-linux-x86_64.sh
          ./bazel-0.19.1-installer-linux-x86_64.sh --user
          echo 'export PATH="$PATH:$HOME/bin' >> ~/.bashrc