name: Docker image scanner [Docker Scout]

on:
  schedule:
    - cron: '0 0 * * *' # This will run the workflow daily at midnight (UTC)
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string
        default: dirigiblelabs/dirigible
      tag:
        required: true
        type: string
        default: latest

run-name: 'Scan image [${{ inputs.image }}] tag [${{ inputs.tag }}]'

jobs:
  scan-image:
    runs-on: ubuntu-${{ inputs.tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Scout Quickview and CVEs
        uses: docker/scout-action@v1
        with:
          command: quickview,cves
          image: ${{ inputs.image }}:${{ inputs.tag }}
          sarif-file: sarif.output.json
          summary: true
          only-fixed: true

      - name: Docker Scout SBOM
        uses: docker/scout-action@v1
        with:
          command: sbom
          image: ${{ inputs.image }}:${{ inputs.tag }}
          output: sbom.json

      - name: Docker Scout Recommendations
        uses: docker/scout-action@v1
        with:
          command: recommendations
          image: ${{ inputs.image }}:${{ inputs.tag }}

      - name: Upload Docker Scout SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif.output.json
