name: Pre-release

on:
  push:
    tags:
    - 'pre*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Set up JDK 13
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '13'
        pg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        architecture: x64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
    - name: Set Multi-Builder Docker Buildx
      run: docker buildx create --use --name multi-builder --platform linux/arm64,linux/amd64,linux/arm64/v8
    - name: Set Dirigible Version
      run: echo DIRIGIBLE_VERSION=${GITHUB_REF#refs/*/} | tr pre " " | sed 's/   //'  >> $GITHUB_ENV

    - name: Build Dirigible
      run: mvn clean install -Dmaven.javadoc.skip=false

#-----------------Publish to DockerHub-------------------#

    - name: Docker Login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Push Dirigible
      run: |
        cd releng/server-all
        docker build --load --build-arg DIRIGIBLE_VERSION=$DIRIGIBLE_VERSION -t dirigible-base-platform -f Dockerfile-base .
        docker tag dirigible-base-platform dirigiblelabs/dirigible-base-platform:$DIRIGIBLE_VERSION
        docker push dirigiblelabs/dirigible-base-platform:$DIRIGIBLE_VERSION
        docker build --load --build-arg DIRIGIBLE_VERSION=$DIRIGIBLE_VERSION -t dirigible-all .
        docker tag dirigible-all dirigiblelabs/dirigible-all:$DIRIGIBLE_VERSION
        docker push dirigiblelabs/dirigible-all:$DIRIGIBLE_VERSION
        docker image prune -a -f
        cd ../../
    - name: Push Dirigible - Keycloak
      run: |
        cd releng/server-keycloak-all
        docker build --load --build-arg DIRIGIBLE_VERSION=$DIRIGIBLE_VERSION -t dirigible-base-platform-keycloak -f Dockerfile-base .
        docker tag dirigible-base-platform-keycloak dirigiblelabs/dirigible-base-platform-keycloak:$DIRIGIBLE_VERSION
        docker push dirigiblelabs/dirigible-base-platform-keycloak:$DIRIGIBLE_VERSION
        docker build --load --build-arg DIRIGIBLE_VERSION=$DIRIGIBLE_VERSION -t dirigible-keycloak .
        docker tag dirigible-keycloak dirigiblelabs/dirigible-keycloak:$DIRIGIBLE_VERSION
        docker push dirigiblelabs/dirigible-keycloak:$DIRIGIBLE_VERSION
        docker image prune -a -f
        cd ../../
    - name: Push Dirigible - Keycloak - Runtime
      run: |
        cd releng/server-runtime-keycloak
        docker build --load --build-arg DIRIGIBLE_VERSION=$DIRIGIBLE_VERSION -t dirigible-base-platform-runtime-keycloak -f Dockerfile-base .
        docker tag dirigible-base-platform-runtime-keycloak dirigiblelabs/dirigible-base-platform-runtime-keycloak:$DIRIGIBLE_VERSION
        docker push dirigiblelabs/dirigible-base-platform-runtime-keycloak:$DIRIGIBLE_VERSION
        docker build --load --build-arg DIRIGIBLE_VERSION=$DIRIGIBLE_VERSION -t dirigible-runtime-keycloak .
        docker tag dirigible-runtime-keycloak dirigiblelabs/dirigible-runtime-keycloak:$DIRIGIBLE_VERSION
        docker push dirigiblelabs/dirigible-runtime-keycloak:$DIRIGIBLE_VERSION
        docker image prune -a -f
        cd ../../

#-----------------Publish to DockerHub-------------------#

#----------------Publish Helm Release------------------#

    - name: Helm tool installer
      uses: Azure/setup-helm@v3
    - name: Helm Charts Release - Checkout gh-pages
      run: |
        mkdir charts-temp
        cp -r releng/helm-charts/ charts-temp/

        #### Git Checkout Workaround
        git add .github/
        git add .reuse/
        git add LICENSES/
        git add api/
        git add ext/
        git add groups/
        git add ide/
        git add logo/
        git add modules/
        git add releng/
        git add resources/
        git add templates/
        git reset --hard
        ####

        git fetch
        git checkout gh-pages
        
        cp charts/* .

    - name: Helm Charts Release - Set Chart Version - Dirigible
      run: |
        cd charts-temp/helm-charts/dirigible/
        find *.yaml -type f -exec sed -i ''s/#{DirigibleVersion}#/${{ env.DIRIGIBLE_VERSION }}/g'' {} \;

    - name: Helm Charts Release
      run: |

        cp charts/* charts-temp/helm-charts/
        cd charts-temp/helm-charts/

        helm package dirigible
        cd ..
        helm repo index helm-charts/ --url https://eclipse.github.io/dirigible/charts
        
        cp helm-charts/index.yaml ../.
        cp helm-charts/dirigible-$DIRIGIBLE_VERSION.tgz ../charts/

        cd ..
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add index.yaml
        git add charts/
        git commit -m "Updates Helm Charts - Release $DIRIGIBLE_VERSION"
        git push origin gh-pages

        git add .
        git reset --hard
        git checkout master
#----------------Publish Helm Release------------------#

